# Generated by Django 5.1 on 2024-08-20 23:53

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNumber', models.CharField(max_length=100)),
                ('ProductNumber',  models.CharField(max_length=100)),
                ('WiseItemNumber',  models.CharField(max_length=100)),
                ('MainframeDescription' ,models.CharField(max_length=100)),
                ('ManufacturerName',  models.CharField(max_length=500)),
                ('WinItemName',  models.CharField(max_length=500)),
                ('SimilarityScore',  models.CharField(max_length=500)),
                ('ItemStatus',  models.CharField(max_length=100)), 
                ('idManufacturer', models.CharField(max_length=100)),          
                ('ComodityNumber', models.TextField()), 
                ('CatalogNnumber',models.TextField()),
                ('UPC',models.TextField()),
                ('VENDOR_ITEM_NUMBER',models.TextField()),  
                ('VENDOR_NUMBER',models.TextField()),
            ],
        ),
    ]


# ('CategoryKey', models.CharField(max_length=100)),
#  ('PIK',  models.CharField(max_length=100)),
#                 ('ItemLCP',  models.CharField(max_length=100)),
#                 ('CatalogNnumber',  models.CharField(max_length=100)),
#                 ('OrderNumber',  models.CharField(max_length=100)),
#                 ('Brand',  models.CharField(max_length=500)),
#  ('idManufacturer',  models.CharField(max_length=100)),